# Generated by Django 5.0.4 on 2025-02-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
            ],
        ),
        migrations.CreateModel(
            name="TrailerInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата получения страховки"
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания страховки"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.person",
                        verbose_name="Человек",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TruckInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата получения страховки"
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания страховки"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.person",
                        verbose_name="Человек",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата получения визы"
                    ),
                ),
                (
                    "visa_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания визы"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.person",
                        verbose_name="Человек",
                    ),
                ),
            ],
        ),
    ]
