# Generated by Django 5.0.4 on 2025-02-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailerinsurance",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.person",
                verbose_name="Человек",
            ),
        ),
        migrations.AlterField(
            model_name="truckinsurance",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.person",
                verbose_name="Человек",
            ),
        ),
        migrations.AlterField(
            model_name="visa",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.person",
                verbose_name="Человек",
            ),
        ),
    ]
