# Generated by Django 5.0.4 on 2025-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0002_alter_trailerinsurance_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trailerinsurance",
            name="person",
        ),
        migrations.RemoveField(
            model_name="truckinsurance",
            name="person",
        ),
        migrations.AddField(
            model_name="trailerinsurance",
            name="trailer_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер прицепа"
            ),
        ),
        migrations.AddField(
            model_name="truckinsurance",
            name="truck_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Номер машины (тягач)",
            ),
        ),
    ]
