# Generated by Django 5.0.4 on 2025-02-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0003_remove_trailerinsurance_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FreightCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SubCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "consignee_info",
                    models.TextField(
                        blank=True,
                        verbose_name="Грузополучатель, адрес, телефон, контактное лицо",
                    ),
                ),
                (
                    "loading_address",
                    models.TextField(blank=True, verbose_name="Адрес пункта погрузки"),
                ),
                (
                    "sender_contact_info",
                    models.TextField(
                        blank=True, verbose_name="Контактное лицо и телефон Отправителя"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcompanies",
                        to="visas.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consignee",
                    models.TextField(
                        blank=True,
                        verbose_name="Грузополучатель, адрес, телефон, контактное лицо",
                    ),
                ),
                (
                    "loading_address",
                    models.TextField(blank=True, verbose_name="Адрес пункта погрузки"),
                ),
                (
                    "sender_contact",
                    models.TextField(
                        blank=True, verbose_name="Контактное лицо и телефон Отправителя"
                    ),
                ),
                (
                    "loading_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата погрузки"
                    ),
                ),
                (
                    "cargo_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование груза"
                    ),
                ),
                (
                    "cargo_details",
                    models.TextField(
                        blank=True, verbose_name="Вес, размеры, объём, стоимость"
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Стоимость фрахта",
                    ),
                ),
                (
                    "insurance",
                    models.BooleanField(
                        default=False, verbose_name="Страхование груза"
                    ),
                ),
                (
                    "delivery_term",
                    models.CharField(
                        default="12-14 дней",
                        max_length=50,
                        verbose_name="Срок доставки",
                    ),
                ),
                (
                    "transportation_features",
                    models.TextField(
                        default="Грузить в один ярус, на наши коробки не ставить коробки и паллеты других отправителей.",
                        verbose_name="Особенности транспортировки груза",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="100% оплата по факту прибытия",
                        max_length=50,
                        verbose_name="Условия оплаты",
                    ),
                ),
                (
                    "freight_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.freightcompany",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visas.route",
                    ),
                ),
                (
                    "subcompany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.subcompany",
                    ),
                ),
            ],
        ),
    ]
