# Generated by Django 5.0.4 on 2025-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0004_company_freightcompany_route_subcompany_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер машины"
                    ),
                ),
            ],
        ),
    ]
