# Generated by Django 5.0.4 on 2025-03-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0005_carnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailerinsurance",
            name="trailer_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.carnumber",
                verbose_name="Машина",
            ),
        ),
        migrations.AlterField(
            model_name="truckinsurance",
            name="truck_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.carnumber",
                verbose_name="Машина",
            ),
        ),
    ]
