# Generated by Django 5.0.4 on 2025-03-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0006_alter_trailerinsurance_trailer_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="car_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="visas.carnumber",
                verbose_name="Номер машины",
            ),
        ),
    ]
