# Generated by Django 5.0.4 on 2025-03-02 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0007_person_car_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="car_number",
        ),
    ]
