# Generated by Django 5.0.4 on 2025-03-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0008_remove_person_car_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Отправлено", "Отправлено"),
                            ("Доставлен", "Доставлен"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "departure",
                    models.CharField(max_length=100, verbose_name="Место отправки"),
                ),
                (
                    "destination",
                    models.CharField(max_length=100, verbose_name="Место получения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.carnumber",
                        verbose_name="Машина",
                    ),
                ),
            ],
        ),
    ]
