# Generated by Django 5.0.4 on 2025-03-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0009_trackingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingrequest",
            name="departure_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выезда"),
        ),
        migrations.AlterField(
            model_name="trackingrequest",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="visas.carnumber",
                verbose_name="Машина",
            ),
        ),
    ]
