# Generated by Django 5.0.4 on 2025-03-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0011_cargoinfo_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название шаблона этапа",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="stage",
            name="name",
        ),
        migrations.AddField(
            model_name="stage",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="visas.stagetemplate",
                verbose_name="Шаблон этапа",
            ),
        ),
    ]
