# Generated by Django 5.0.4 on 2025-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0012_stagetemplate_remove_stage_name_stage_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoinfo",
            name="file",
            field=models.FileField(upload_to="cargo_files/", verbose_name="Файл груза"),
        ),
    ]
