# Generated by Django 5.0.4 on 2025-05-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0013_alter_cargoinfo_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата техосмотра"
                    ),
                ),
                (
                    "inspection_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания техосмотра"
                    ),
                ),
                (
                    "trailer_number",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.carnumber",
                        verbose_name="Машина (Прицеп)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TruckInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата техосмотра"
                    ),
                ),
                (
                    "inspection_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания техосмотра"
                    ),
                ),
                (
                    "truck_number",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visas.carnumber",
                        verbose_name="Машина (Тягач)",
                    ),
                ),
            ],
        ),
    ]
