# Generated by Django 5.0.4 on 2025-05-11 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0014_trailerinspection_truckinspection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="truckinspection",
            old_name="inspection_date",
            new_name="inspection_issue_date",
        ),
    ]
