# Generated by Django 5.0.4 on 2025-05-11 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0015_rename_inspection_date_truckinspection_inspection_issue_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trailerinspection",
            old_name="inspection_date",
            new_name="inspection_issue_date",
        ),
    ]
