# Generated by Django 5.0.4 on 2025-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "visas",
            "0016_rename_inspection_date_trailerinspection_inspection_issue_date",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер прицепа"
                    ),
                ),
            ],
        ),
    ]
