# Generated by Django 5.0.4 on 2025-05-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0017_trailernumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailerinspection",
            name="trailer_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.trailernumber",
                verbose_name="Машина (Прицеп)",
            ),
        ),
        migrations.AlterField(
            model_name="trailerinsurance",
            name="trailer_number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visas.trailernumber",
                verbose_name="Машина",
            ),
        ),
    ]
