# Generated by Django 5.0.4 on 2025-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0018_alter_trailerinspection_trailer_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(max_length=255, unique=True, verbose_name="ФИО"),
        ),
    ]
