# Generated by Django 5.0.4 on 2025-05-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0019_alter_person_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailernumber",
            name="car_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trailers",
                to="visas.carnumber",
            ),
        ),
    ]
