# Generated by Django 5.0.4 on 2025-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0020_trailernumber_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Отправлено", "Отправлено"), ("Доставлен", "Доставлен")],
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
