# Generated by Django 5.0.4 on 2025-05-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0021_alter_trackingrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
