# Generated by Django 5.0.4 on 2025-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0022_stage_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="is_active",
        ),
        migrations.AddField(
            model_name="stage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
