# Generated by Django 5.0.4 on 2025-05-14 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0023_remove_stage_is_active_stage_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="is_deleted",
        ),
    ]
