# Generated by Django 5.0.4 on 2025-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0024_remove_stage_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingrequest",
            name="archive",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
        migrations.AlterField(
            model_name="trackingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Отправлено", "Отправлено"),
                    ("Доставлено", "Доставлено"),
                    ("Завершено", "Завершено"),
                ],
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
