# Generated by Django 5.0.4 on 2025-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0025_trackingrequest_archive_alter_trackingrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingrequest",
            name="archive",
        ),
        migrations.AlterField(
            model_name="trackingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Отправлено", "Отправлено"),
                    ("Доставлено", "Доставлено"),
                    ("Завершено", "Завершено"),
                    ("Архив", "Архив"),
                ],
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
