# Generated by Django 5.0.4 on 2025-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0026_remove_trackingrequest_archive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingrequest",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
        migrations.AlterField(
            model_name="trackingrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Отправлено", "Отправлено"), ("Доставлен", "Доставлен")],
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
