# Generated by Django 5.0.4 on 2025-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0027_trackingrequest_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freightcompany",
            name="contact_info",
            field=models.TextField(blank=True, verbose_name="Реквизиты компании"),
        ),
    ]
