# Generated by Django 5.0.4 on 2025-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visas", "0028_freightcompany_contact_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingapplication",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
    ]
